apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: between-machines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:donhamiltoniii/between-machines.git
    targetRevision: HEAD
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: between-machines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
