apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-acorn
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: dev
        branch: develop
        namespace: project-acorn-dev
      - environment: prod
        branch: main
        namespace: project-acorn-prod
  template:
    metadata:
      name: 'project-acorn-{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/donhamiltoniii/project-acorn
        targetRevision: '{{branch}}'
        path: 'k8s/overlays/{{environment}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m